{
  "id": 1,
  "time": "2023-01-03 20:59:59",
  "user": "zukunft.com system test",
  "text": "the log text that describes the problem for the user or system admin",
  "description": null,
  "trace": "the technical trace back description for debugging",
  "prg_part": "name of the function that has caused the exception",
  "owner": "",
  "status": "2"
}